version: "3.8"

networks:
  apigateway_system_network:
    external: true

services:
  image_server:
    ports:
      - "5000:5000"
    env_file:
      - ./env.prod
    hostname:
      image_service
    networks:
      - apigateway_system_network